import color from '../../styles/color';

export default {
  maincontainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  backgroundstyle: {
    flex: 1,
    resizeMode: 'cover',
    flexDirection: 'column',
  },
  toolbar: {
    width: '100%',
    height: 90,
    backgroundColor: '#121212',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  topBar: {
    width: 30,
    height: 30,
    backgroundColor: '#252525',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  topLeft: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 34,
    width: 60,
    backgroundColor: '#252525',
    borderRadius: 70,
    marginLeft: -17,
    padding: 7,
  },
  topLeftText: {
    color: 'white',
    fontWeight: '600',
  },
  cryptoText: {
    backgroundColor: '#262626',
    width: 100,
    height: 35,
    padding: 4,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  CoinText: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  tooltxt: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 18,
    marginTop: 25,
  },
  backbtn: {
    width: 40,
    height: 50,
    justifyContent: 'center',
    marginTop: 25,
  },
  morebtn: {
    width: 40,
    height: 50,
    justifyContent: 'center',
  },
  backbtnimg: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    aspectRatio: 1,
    // marginStart: 10,
    tintColor: '#333333',
  },
  forwardarrowImg: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    aspectRatio: 1.5,
    marginStart: 10,
    transform: [{rotate: '180deg'}],
    tintColor: '#333333',
  },
  forwardArrowImg: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    aspectRatio: 0.5,
    marginStart: 10,
    transform: [{rotate: '180deg'}],
    tintColor: '#333333',
  },
  borderbackground: {
    width: '100%',
    height: 0.3,
    marginTop: 8,
    backgroundColor: '#56514D',
  },
  termconditiontxt: {
    fontSize: 13,
    textAlign: 'left',
    color: '#8D8D8D',
    marginTop: 5,
  },
  termconditionheadingtxt: {
    fontSize: 16,
    textAlign: 'left',
    marginTop: 15,
    color: '#333333',
  },
  bottomborderview: {
    width: '100%',
    backgroundColor: 'gray',
    height: 0.5,
    marginTop: 5,
  },
  contrycodetxt: {
    color: '#333333',
    fontSize: 15,
    marginEnd: 5,
  },
  countrytextview: {
    width: '20%',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  countrynametxt: {
    color: '#333333',
    fontSize: 15,
    marginStart: 18,
  },
  countryImage: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    resizeMode: 'contain',
    marginStart: 5,
  },
  mainrenderitem: {
    width: '100%',
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
  },
  firstview: {
    width: '80%',
    alignItems: 'center',
    flexDirection: 'row',
  },
  statecnametxt: {
    color: '#333333',
    fontSize: 15,
    marginStart: 1,
  },
  SearchBar: {
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#121212',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 25,
  },
  searchbox: {
    height: 45,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 12,
    marginTop: 5,
    paddingStart: 15,
  },
  notificationImg: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    aspectRatio: 1,
    tintColor: '#333333',
  },
  continuebtn: {
    height: 45,
    backgroundColor: color.themeVoilet,
    alignItems: 'center',
    marginTop: 40,
    justifyContent: 'center',
    borderRadius: 5,
  },
};
